app = "seat-reserve-service"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DB_POOL_SIZE = "30"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/actuator/health/readiness"
  protocol = "http"
  timeout = "3s"

[vm]
  size = "shared-cpu-1x"
  memory = "1024mb"
